### ISSUE TITLE
Create nav bar

### ISSUE THREAD

**Issue by gfunue** [gfunue/authapp#1]

**Comment by PhilipAgyekum** [comment]
@gfunue The navigation bar should render on every page and dynamically adjust its content according to the user's login state. When the user is logged in, the navigation bar should display a logout button and a search option. Conversely, when the user logs out, the navigation bar should disappear.  I can implement this also I think we can make this navbar better easily .. thank you. Let me know your thoughts 
![image](https://github.com/gfunue/authapp/assets/159867860/3b0f7b8e-0678-4bb0-82f0-0559883c47fa)
